project:
  type: website
  output-dir: docs
website:
  title: "H's notes"
  site-url: https://hangenyuu.github.io/h_notes/
  description: H's Notes on Deep Learning
  navbar:
    right:
      - about.qmd
      - now.qmd
      - icon: github
        href: https://github.com/HangenYuu/
      - icon: linkedin
        href: https://www.linkedin.com/in/phnghung/
      - icon: twitter
        href: https://twitter.com/HangenYuu
comments:
  giscus: 
    repo: HangenYuu/h_notes
highlight-style: github
format:
  html:
    theme: lux
    css: styles.css



