project:
  type: website
  output-dir: docs
website:
  title: "Hung's Playground"
  navbar:
    right:
      - about.qmd
      - now.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: sketchy
    css: styles.css



