project:
  type: website
  output-dir: docs
website:
  title: "H's notes"
  site-url: https://hangenyuu.github.io/h_notes/
  description: H's Notes on Deep Learning
  margin-header: subscribe.html
  navbar:
    right:
      - about.qmd
      - now.qmd
      - icon: box-arrow-up-right
        href: https://h-notes-on-dsa.netlify.app/
      - icon: github
        href: https://github.com/HangenYuu/
      - icon: linkedin
        href: https://www.linkedin.com/in/phnghung/
      - icon: twitter
        href: https://twitter.com/HangenYuu
  page-footer:
    left: "Blog made with [Quarto](https://quarto.org/), © Copyright 2022 Pham Nguyen Hung. License: GNU General Public License v3.0"
comments:
  giscus: 
    repo: HangenYuu/h_notes
highlight-style: github
format:
  html:
    theme:
      light: [lux, light.scss]
      dark: [darkly, dark.scss]