project:
  type: website
  output-dir: docs
website:
  title: "H's notes"
  navbar:
    right:
      - about.qmd
      - now.qmd
      - icon: github
        href: https://github.com/HangenYuu/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: lux
    css: styles.css



