---
title: "Journal"
date: "2022-10-22"
draft: true
---
# Journal
Just a place to explore my thought for every day.
## 23/10/2022
It's hard to study a thing top-down. I am disillusioned. I was meant to write "a bit" but then I stopped myself. Was I being polite? Who taught me to be like this?
Well back to it. I am tired. The top-down approach is something natural made unnatural after 2 decades of unnatural teaching. I hate the way my skin opposed to it, the same I did it with data structures and algorithms. I did not feel any progress at all in this regard. Meanwhile, another day passed...
Now the hard part. Was I disappointed because I was not invited to the party? Truthfully, yes. I thought I am a friend. Now I learn the truth. I am just a convenient being under some circumstances to serve some purpose for them. Otherwise, I am no one but a stranger. Fair. I am upset. I am sad. I am surprised and hurt. And it is likely that I will feel it for a long time.
However, the power is within me. I am the one calling the shot, not her. I am the one deciding who's worth my time and attention, not her. I will do my job, and stop caring for whatever happened to her, and them while they were with her any more.
And it is not a "play dumb to have peace" thing. I will know fully what she does or what they do. I will care, instinctively. I just stop caring the moment I realize.
Hold your head high. You have goals and ambitions. In a dark night alone, that's enough.