---
title: "Daily translation of Meditations to Vietnamese"
subtitle: "Translation is an act to engage more deeply"
author: "Pham Nguyen Hung"
date: "2022-11-07"
categories: [daily]
---
## 07 - Nov - 2022
> "Don't trust in your reputation, money, or position, but in the strength that is yours—namely, your judgements about the things that you control and don't control. For this alone is what makes us free and unfettered, that picks us up by the neck from the depths and lifts us eye to eye with the rich and powerful." — EPICTETUS, *DISCOURSES*, 3.26.34–35

Đừng tin vào danh vọng, tiền bạc, hay vị trí [của bản thân], mà hãy tin vào sức mạnh mà con nắm giữ—khả năng phân biệt giữa thứ mà con có thể kiểm soát và thứ mà con không thể. Bởi đây là thứ duy nhất giúp chúng ta được tự do và không bị ràng buộc, là thứ duy nhất kéo chúng ta thoát khỏi vực thẳm và đưa chúng ta ngang hàng với những kẻ giàu có và quyền lực.

It is something that is expected from Epictetus - the emphasis on the dichotomy of control. What surprises me is the last phrase. The ability to exercise the dichotomy of control and act accordingly gives us power and wealth. It is all based on the same principle: to have more, you can acquire more, or you can want less.

## 08 - Nov - 2022
> "Remember that you are an actor in a play, playing a character according to the will of the playwright—if a short play, then it’s short; if long, long. If he wishes you to play the beggar, play even that role well, just as you would if it were a cripple, a honcho, or an  everyday person. For this is your duty, to perform well the character assigned you. That selection belongs to another." — EPICTETUS, *ENCHIRIDION*, 17

Hãy nhớ rằng con là một diễn viên trong một vở kịch [mang tên cuộc đời], diễn một vai theo ý muốn của người viết kịch—nếu đó là một vở kịch ngắn, thì diễn ngắn; nếu nó dài, thì diễn dài. Nếu người viết kịch muốn con đóng vai một kẻ ăn mày, vậy thì hãy diễn vai đó thật tốt, cũng tương tự như vậy nếu con nhận được vai kẻ bị thọt, người đứng đầu, hay chỉ là một người bình thường. Bởi việc diễn thật tốt vai đã được giao chính là nghĩa vụ của con. Việc chọn vai nào [cho con] thuộc về những người khác.

Now the last sentence raised my eyebrows. What? Let's others choose for me? Ins't that antithetical to "Essentialism"? That I need to prioritize my life instead of letting others prioritize it for me! But be calm - Epictetus did not talk about letting others choose. The others here referred to the higher being, chance, luck i.e. anything that we cannot control. It is probable that the course of our life is led to stranger lands because of some accidents. However, we are still in control: we can choose to get back on track after being thrown off-trackor not. That alone is important, that alone is enough.